version: '3.1'

services:
  db:
    image: mysql
    container_name: ren-ie-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: ren-ie-local
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
    # networks:
    #   - local-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ren-ie-app
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/
    # networks:
    #   - local-network

  # dbeaver:
  #   image: dbeaver/cloudbeaver
  #   restart: always
  #   ports:
  #     - 8081:8978
  #   volumes:
  #     - ./src/dbeaver:/opt/cloudbeaver/workspace

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# networks:
#   local-network:
#     driver: bridge